### ISSUE TITLE
Can't locate globalvariables.pl

### ISSUE THREAD

**Issue by ghost** [CSAILVision/LabelMeAnnotationTool#1]
I set up the LableMe annotation tool on the local server. While browsing the tool, I am receiving the error "Unknown objXml.status" and unable to draw a polygon.  Set up files are fine in concern with the possible causes mentioned in the README file. 
In the server error log, I found that globalvariables.pl is used in the perl scripts but it is not in the package. I was wondering if this file supposed to be in the labelme tool or is there a problem with perl installation?

Following is the snippet of the error log:
"Can't locate globalvariables.pl in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.10.0 /usr/local/share/perl/5.10.0 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.10 /usr/share/perl/5.10 /usr/local/lib/site_perl .) at /var/www/public/LabelMe/annotationTools/perl/get_anno_file.cgi line 2., referer: http://myServer.LabelMe/tool.html?collection=LabelMe&mode=f&folder=example_folder&image=img1.jpg"

**Comment by daohu527** [comment]
Addition: If you use a docker and want to mount a volume, you should not use the entire "LabelMeAnnotationTool" dir. If you do this, you will receive the error "Fatal: there are problems with fetch_image.cgi"
