### ISSUE TITLE
Error message: Second argument must be either "get" or "post".

### ISSUE THREAD

**Issue by leetcodersd** [CSAILVision/LabelMeAnnotationTool#11]
Hi all,
I followed the instructions from the website and input the following commands.

=====================================================================
HOMEIMAGES = 'http://people.csail.mit.edu/brussell/research/LabelMe/Images';
HOMEANNOTATIONS = 'http://people.csail.mit.edu/brussell/research/LabelMe/Annotations';
D = LMdatabase(HOMEANNOTATIONS);

=====================================================================

But I constantly got the error messages shown below.

=====================================================================
??? Error using ==> urlread at 43
Second argument must be either "get" or "post".

Error in ==> urldir at 44
    [webpage, status] = urlread(page, 'Timeout', 5);

Error in ==> LMdatabase at 103
            files = urldir(HOMEANNOTATIONS);

===================================================================== 

Any help?

Best,
Kai

**Comment by quantombone** [comment]
Hi Kai,

It seems like your issue is related to the LabelMe Matlab toolbox. (LMdatabase is not defined inside this code repository, which is just the labeling tool).  

What version of Matlab are you using?  I suspect you have an older version.  Just type `version` inside the Matlab prompt and let us know the version.  For example, my version is 8.3.0.532 (R2014a).

**Comment by brussell123** [comment]
Hi Kai,

What's your version of Matlab?  You may have a different version.

Maybe you can try using this line instead:

 [webpage, status] = urlread(page);

Let us know how it goes.

**Comment by leetcodersd** [comment]
Hi brussel123 and quantombone,
Yes it was the version!
Now I've installed the latest version of MATLAB (8.4.0.150421 (R2014b)) and everything works!
My old version is R2010a.
Thanks for your help!

Best,
Kai
