### ISSUE TITLE
Have Trouble in Building Index D with HOMEANNOTATIONS

### ISSUE THREAD

**Issue by leetcodersd** [CSAILVision/LabelMeAnnotationTool#12]
Hi all,

According to the tutorial, after downloading a specific list of folders, I need to build the index with the following instruction.

D = LMdatabase(HOMEANNOTATIONS);

But I couldn't get any annotated images from XML files in ANNOTATIONS folder (see the massage as follow).

1/4, .
 Total images:0, annotation files:0 (with 0 empty xml files)
2/4, E:\Code\LabelMeToolbox-master\LabelMeToolbox-master\annotation\05june05_static_indoor
 Total images:0, annotation files:0 (with 0 empty xml files)
3/4, E:\Code\LabelMeToolbox-master\LabelMeToolbox-master\annotation\dec_static_office
 Total images:0, annotation files:0 (with 0 empty xml files)
LabelMe Database summary:
 Total of 0 annotated images.

Any help on that?

Best,
Kevin

**Comment by leetcodersd** [comment]
The Matlab2014 crushes when using OpenGL. But Matlab2010 works well on this instruction. I guess I need to switch between the two versions a lot...

**Comment by brussell123** [comment]
Is the OpenGL issue related to the LabelMe Matlab toolbox?  If not, then I'll close this issue.
