### ISSUE TITLE
Windows perquisites 

### ISSUE THREAD

**Issue by mtngld** [CSAILVision/LabelMeAnnotationTool#13]
Had a hard time running this on Windows,

It should be stated clearly in the Windows instructions that Imagemagick is required (for the "identify" command) and cygwin should be added to PATH (for cp in windows)

**Comment by brussell123** [comment]
Thanks for your feedback!  I've added your suggestions to the Windows instructions.

Please let me know if you have any further feedback.  We have not done much testing of the annotation tool on Windows, so any help is much appreciated!
