### ISSUE TITLE
missing main.js under the segmentCPP folder 

### ISSUE THREAD

**Issue by xn8812** [CSAILVision/LabelMeAnnotationTool#24]
Hi, 

I am trying to use the grab cut algorithm provided in ./annotationTools/scribble/segmentCPP folder. However, the main.js file is missing. Could you please update it?

**Comment by xavierpuigf** [comment]
Hi,

I have uploaded the main.js file. Note however that the segmentation can be found in ./annotationTools/js/scribble.js in the compute() function. That function is the one being called to segment objects in the main tool
