### ISSUE TITLE
Mode "c" doesn't seem to work as documented

### ISSUE THREAD

**Issue by sirotenko** [CSAILVision/LabelMeAnnotationTool#32]
The documentation say:

> mode=c - Go to next image in the collection (set via the dirlist).
But if we look at the code [here](https://github.com/CSAILVision/LabelMeAnnotationTool/blob/41da81fad950f883e8237777014588a4339cf0b1/annotationTools/perl/fetch_image.cgi#L44), we can see that it actually tries to read the contents of a specific folder:
```perl
elsif($mode eq "c") {
    opendir(DIR,$LM_HOME . "Images/users/$username/$collection") || die("Cannot read collections");
    my @all_images = readdir(DIR);
    closedir(DIR);

    my $c = 0;
    foreach my $i (@all_images) {
	if($i eq $image) {
	    goto next_section;
	}
	$c = $c+1;
    }
  next_section:
    if($c == scalar(@all_images)-1) {
	$c = 1;
    }
    $im_file = $all_images[$c+1];
    $im_dir = $folder;
}
```

**Comment by brianabrams** [comment]
#33

**Comment by xavierpuigf** [comment]
The pull request has been merged now. Thanks!

**Comment by Abhijit-2592** [comment]
Even after the merge the mode C doesn't seem to work properly. It shows problems with fetch_image.cgi.
