### ISSUE TITLE
Click Next Image but URL remains the same

### ISSUE THREAD

**Issue by niuqun** [CSAILVision/LabelMeAnnotationTool#38]
I am running LabelMeAnnotationTool on Ubuntu 14.04 with Apache 2.4. Everything seems perfect except when I finish annotating one image and click the ''Next Image''. The web page updates and the next image shows up correctly. However, it seems that the url remains the same. For example, I have a starting url pointing to 1.jpg (http://mywebsite.com/tool.html?collection=LabelMe&mode=f&folder=example_images&**image=1.jpg**). After I click next image, the second image shows up on the web page but the url indicates that it still points to 1.jpg (http://mywebsite.com/tool.html?collection=LabelMe&mode=f&folder=example_images&**image=1.jpg**) instead of (http://mywebsite.com/tool.html?collection=LabelMe&mode=f&folder=example_images&image=2.jpg). In this case, the annotations of different images are crammed into one file, which is difficult to process. Has anyone got any clues on this?

**Comment by hofingermarkus** [comment]
I had a similar setup and as far as I remember the XML files are created according to the true images name. (However I did not use collection mode)

But yes I also had this behavior of the URL staying the same.
An updated URL or some line indicating the true image name would be great, also a back button...

**Comment by Abhijit-2592** [comment]
+1

**Comment by shiwenhao** [comment]
@niuqun I hava a start url(http://localhost/LabelMeAnnotationTool/tool.html?collection=LabelMe&mode=i&folder=test&image=1.jpg).After I click next image,the second image point to http://localhost/LabelMeAnnotationTool/tool.html?collection=LabelMe&mode=i&folder=example_folder&image=img2.jpg,My images is in "test" folder，but next image point to example_folder.
Can you help me?
Thank you very much !

**Comment by Abhijit-2592** [comment]
Change mode to 'f' and remove the "collection=foo"

**Comment by shiwenhao** [comment]
@Abhijit-2592 Thanks,it works

**Comment by Abhijit-2592** [comment]
@niuqun did you find any work arounds? To update the URL for every new image in the folder?

**Comment by niuqun** [comment]
@Abhijit-2592 @shiwenhao Sorry for the late reply. I have not found any solutions to deal with it yet and  have moved to other projects.

**Comment by Abhijit-2592** [comment]
@niuqun oh ok. Please drop by any solution if you find one in the future. 
I have one bad work around. I just change the image name everytime instead of pressing the next button

**Comment by hofingermarkus** [comment]
I guess for many cases it would already help if the current image name would be displayed somewhere on the webpage, maybe as an option. The URL update would be perfect, but displaying the current name e.g. in or above the list of "Polygons in this image" would already help a lot.

**Comment by xavierpuigf** [comment]
Hi, the url is not updated to speed up switching to the next image. We have added a flag that shows the image name when active instead. Add showimgname=true in your url to show the name.

**Comment by hofingermarkus** [comment]
Thank your for adding this option! Since it is very usefull, it could be worth adding it to documentation in the Readme.md as well...
