### ISSUE TITLE
Fatal: there are problems with fetch_image.cgi

### ISSUE THREAD

**Issue by Angefonce** [CSAILVision/LabelMeAnnotationTool#43]
I installed LabelMe on AWS based on the instructions given on github.

However, whenever I am trying to call <address>/tool.html?collection=LabelMe&model=f&folder=example_folder&image=img1.jpg

I am facing this box:
Fatal: there are problems with fetch_image.cgi.

I tried other modes, but the result was the same.

When I try to access images individually, I can do that. When I annotate, annotations field reflects the xml image of that image.

**Comment by scott2008** [comment]
Hello did you solved the problem? i have same problems

**Comment by physicso** [comment]
Don't forget to 'make' if you made any change :)

**Comment by karhohs** [comment]
@Angefonce @scott2008 

I ran into the same `Fatal: there are problems with fetch_image.cgi.` on Ubuntu 16.04 from an AWS instance.

I found another issue https://github.com/CSAILVision/LabelMeAnnotationTool/issues/16 that led me to an answer:

`sudo apt-get install libcgi-session-perl`

For future troubleshooting the exact error can be found in the apache log found at `/var/log/apache2/error.log`. The critical information was in the log was `Can't locate CGI.pm in @INC (you may need to install the CGI module)`

**Comment by nbandaru1h** [comment]
I have the same issue but this solution did not work for me. Any ideas?
