### ISSUE TITLE
Fatal: there are problems with fetch_image.cgi

### ISSUE THREAD

**Issue by scott2008** [CSAILVision/LabelMeAnnotationTool#45]
Hello, I am using Ubuntu 16 04

So, When i typed server@domain/LabelMeAnnotationTool/tool.html, i get 

http://server@domain/LabelMeAnnotationTool/tool.html?collection=LabelMe&mode=i&folder=null&image=null then
I get message Fatal: there are problems with fetch_image.cgi when web-page opening and on each of Next image clicks .

How do I solve this problem thx..

**Comment by karhohs** [comment]
@scott2008, I think this is related to issue #16 and #43. The fix for me involved installing a package:

`sudo apt-get install libcgi-session-perl`

**Comment by AndreV84** [comment]
Does it resolve the issue if using Ubuntu 16.04?
In my case the message persists.

**Comment by nbandaru1h** [comment]
I have this issue and installing that package did not help Any ideas?
