### ISSUE TITLE
hotkey to close polygon

### ISSUE THREAD

**Issue by dobkeratops** [CSAILVision/LabelMeAnnotationTool#66]
If you are currently drawing a polygon, make a key (possibly "Enter") automatically close the polygon (without having to manually click back on the first point) and bring up the label entry dialogue.
e.g. drawing a quad could be 4 aimed clicks, then press 'enter', instead of 5 aimed clicks.

also make 'esc' a hotkey to cancel the whole thing, and 'del' a hotkey to remove the last point.

**Comment by xavierpuigf** [comment]
Currently, 'del' is a hot key for removing the last point. You can automatically close the polygon by doing a right click with the mouse.
