### ISSUE TITLE
Adjusting control points failed when use_attributes=0

### ISSUE THREAD

**Issue by yuhan210** [CSAILVision/LabelMeAnnotationTool#7]
In edit_events.js function AdjustPolygonButton() , we should check if the user's using attributes before get those elements. 

 adjust_objEnter = document.getElementById('objEnter').value;
  if (use_attributes){
     adjust_attributes = document.getElementById('attributes').value;
     adjust_occluded = document.getElementById('occluded').value;
  }

**Comment by brussell123** [comment]
Thanks for pointing this issue out.  We've added this to our list of bugs to fix.

**Comment by xavierpuigf** [comment]
Thank you, this has been resolved
