### ISSUE TITLE
Ubuntu 16.04 Dockerfile

### ISSUE THREAD

**Issue by Abhijit-2592** [CSAILVision/LabelMeAnnotationTool#78]
**This is not an issue!**

Since configuring LabelMe is quite challenging in Ubuntu 16.04, I have a [Dockerfile](https://github.com/Abhijit-2592/dockerfiles/tree/master/labelme) that builds labelme docker Container for **Ubuntu 16.04**. The Dockerfile given in this repo is for **Ubuntu 14.04**.

 @brussell123  how about a pull request?

**Comment by brussell123** [comment]
Great! Sure, do you want to create a PR?

**Comment by Abhijit-2592** [comment]
yeah I will create a PR
