### ISSUE TITLE
Online version no new collection?

### ISSUE THREAD

**Issue by MoWizsubhi84** [CSAILVision/LabelMeAnnotationTool#81]
Hello, I have accessed the web online version but I don't see the option to create a new collection and add new images?
any workaround this?
pls advise
thanks

**Comment by brussell123** [comment]
There is an issue with creating new collections that we are working to resolve now. Please stay tuned.

**Comment by brussell123** [comment]
There is an issue with the online web version we are working to resolve.

**Comment by xavierpuigf** [comment]
You should be able to create collections again.
