### ISSUE TITLE
Can't run dirlist

### ISSUE THREAD

**Issue by anchpop** [CSAILVision/LabelMeAnnotationTool#89]
I run

`(general) root@ubuntu-1:/var/www/html/LabelMeAnnotationTool/annotationTools/sh# ./populate_dirlist.sh`

And this is the output:

```
[all my image files]
ls: cannot access '../../VLMFrames': No such file or directory
```

Running `./populate_dirlist.sh my_collection.txt example_folder` fails similarly. What is `VLMFrames` supposed to be?

**Comment by theomessin** [comment]
Any sort of update on this?

**Comment by theomessin** [comment]
Can someone like @xavierpuigf or @brussell123 close this issue. It's hogging my dashboard for no reason.

**Comment by xavierpuigf** [comment]
Thanks for noticing. I commented out the lines
