### ISSUE TITLE
Web based Tool, New collection isn't showing.

### ISSUE THREAD

**Issue by salman-ghauri** [CSAILVision/LabelMeAnnotationTool#90]
Hi,
Few days back I signed up on http://labelme2.csail.mit.edu and created a new collection, uploaded images and labelled them. It well smoothly. Today I wanted to do the same, but when I created a new collection I saw the message "New collection created" but the collection didn't show up. I tried with another account and got same thing.
Any idea about this?

**Comment by xavierpuigf** [comment]
Thank you for the feedback! This should be solved now.

**Comment by KyleAshley** [comment]
It looks like this same issue is occurring again. On http://labelme2.csail.mit.edu, when I attempt to create a new collection, or add pictures to an existing one nothing happens. The dialogue 'New collection created' appears but it is not actually created.

**Comment by xavierpuigf** [comment]
Thanks for notifying! The issue is solved now.
