### ISSUE TITLE
Display problems in Chrome 69

### ISSUE THREAD

**Issue by atekoa** [CSAILVision/LabelMeAnnotationTool#94]
It seems that from the Chrome 69 the images do not show well, load correctly but you can barely see a square of 1px where the image should be

Has anyone else found this same problem? With Chrome 68 and Firefox 47 it is displayed correctly...

Thanks in advance

**Comment by linusmartensson** [comment]
Same issue here, @atekoa 
It looks like a "z-index:-3" is applied on imcanvas, placing the whole canvas behind the background. Not sure why the CSS is there in the first place.

**Comment by srvanderplas** [comment]
I'm having this issue as well. I believe it also happens on Safari. Anyone have any clue how to fix the LabelMe backend so that this doesn't happen?

**Comment by atekoa** [comment]
I solved it by adding the following code
`main_media.Zoom ('adjusted');`
on line 101 in the File 
https://github.com/CSAILVision/LabelMeAnnotationTool/blob/master/annotationTools/js/image.js

**Comment by srvanderplas** [comment]
That didn't work for me; with the addition of that line, the picture no
longer loads at all.

**Comment by atekoa** [comment]
Check also this:
[commit/facb876341f58188173175e2d68a9282a7e15824](https://github.com/CSAILVision/LabelMeAnnotationTool/commit/facb876341f58188173175e2d68a9282a7e15824)

**Comment by srvanderplas** [comment]
That one did it even in absence of the change you suggested. Thanks!
