### ISSUE TITLE
labelme not saving xml annotation on ubuntu 18.04

### ISSUE THREAD

**Issue by mailtohrishi** [CSAILVision/LabelMeAnnotationTool#95]
Hi
    I installed LabelMe on a machine running Ubuntu 18.04, using the instructions provided on github for ubuntu 16.04. But while I am able to draw the polygon/bbox, it does not get saved on the server end (in the Annotations/ subdirectory) as an xml file. No such problem happens when I run LabelMe on a machine having ubuntu 16.04, using exactly the same set of installation instructions.
What could be failing?

**Comment by simonlousky** [comment]
same here, any solutions?

**Comment by mailtohrishi** [comment]
From apache error logs, the problem was found to be location of globalvariables.pl file. It can be solved by looking at a sibling problem (I fixed it that way)
https://github.com/CSAILVision/LabelMeAnnotationTool/issues/1
